site_name: Singleton Service
site_description: Modern and type-safe abstraction for building singleton services in Python
site_url: https://singleton-service.dev
repo_name: vduseev/singleton-service
repo_url: https://github.com/vduseev/singleton-service

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - toc.follow
    - toc.integrate

nav:
  - Home: index.md
  - Install: install.md
  - Quick Start: quickstart.md
  - Tutorial:
    - tutorial/index.md
    - Your First Service: tutorial/first-service.md
    - Adding Dependencies: tutorial/dependencies.md
    - Initialization Order: tutorial/initialization-order.md
    - Health Checks: tutorial/health-checks.md
    - Error Handling: tutorial/error-handling.md
    - Testing Services: tutorial/testing.md
  - Concepts:
    - concepts/index.md
    - The Singleton Pattern: concepts/singleton-pattern.md
    - Dependency Injection: concepts/dependency-injection.md
    - Service Initialization: concepts/initialization.md
    - Error Handling: concepts/error-handling.md
    - Best Practices: concepts/best-practices.md
  - Examples:
    - examples/index.md
    - Weather Service: examples/weather-service.md
    - Database Service: examples/database-service.md
    - Auth Service: examples/auth-service.md
    - User Service: examples/user-service.md
    - Background Worker: examples/background-worker.md
    - Web Server: examples/web-server.md
    - CLI Application: examples/cli-application.md
    - Testing Services: examples/testing-services.md
    - Service Composition: examples/service-composition.md
  - API Reference:
    - api/index.md
    - BaseService: api/base-service.md
    - Decorators: api/decorators.md
    - Exceptions: api/exceptions.md
    - BaseRunnable: api/base-runnable.md
  - Advanced:
    - advanced/index.md
    - Circular Dependencies: advanced/circular-dependencies.md
    - Async Services: advanced/async-services.md
    - Performance: advanced/performance.md
    - Debugging: advanced/debugging.md
    - Migration Guide: advanced/migration-guide.md
  - Changelog: changelog.md
  - Contributing: contributing.md
  - Help: help.md

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_signature_annotations: true
            separate_signature: true
            show_root_heading: true
            show_root_full_path: false
            show_source: false
            show_bases: true
            show_inheritance_diagram: false
  - minify:
      minify_html: true

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - extra/custom.css

extra_javascript:
  - extra/custom.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vduseev/singleton-service
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/singleton-service/
  version:
    provider: mike